### ISSUE TITLE
Make it at least viewable for mobile devices

### ISSUE THREAD

**Issue by TotoWang-hhh** [CodeCrafter-TL/Webintosh#4]
**Describe the bug**
The clicking position badly shifts on mobile devices.

**To Reproduce**
1. Open this page on a mobile device.
2. Try anything.

**Expected behavior**
N/A

**Screenshots**
N/A

**Desktop (please complete the following information):**
 N/A, but should be happen on any vertical browser size.

**Smartphone (please complete the following information):**
 - Device: Xiaomi 14
 - OS: Android 14 (HyperOS)
 - Browser: Google Chrome
 - Version: 124

**Additional context**
If you don't plan to make it compatible for mobile devices, please make a pop-up for those mobile viewers to force them to their PCs.

**Comment by CodeCrafter-TL** [comment]
I think I need to make the desktop interface seamless before developing the mobile version. Thank you for your suggestion!

**Comment by TotoWang-hhh** [comment]
> I think I need to make the desktop interface seamless before developing the mobile version. Thank you for your suggestion!

If you have read my last paragraph, you would know that you can force those mobile viewers to desktop just with a simple pop-up (at least for now). So why not just show a tip on mobile devices but giving buggy experience to mobile viewers? I believe adding a notification with js and show it onn mobile device in the startup page is just a piece of cake.

**Comment by CodeCrafter-TL** [comment]
Yes, I think this method is great! I will add this popup soon, thank you very much for the suggestion!

**Comment by HelloAIXIAOJI** [comment]
Two Chinese people communicating in English in Github issues... (now three

**Comment by TotoWang-hhh** [comment]
> Two Chinese people communicating in English in Github issues... (now three

Congratulations! You are the only one who realized this! 🎉🎉🎉😄🎉🎉🎉

**Comment by SDCOM-0415** [comment]
huh?

**Comment by CodeCrafter-TL** [comment]
I will do it later in version 8.

**Comment by Sean537** [comment]
Has it finished? @CodeCrafter-TL 

I regrettably discovered that the multi-touch support still didn't work on my Safari for iPadOS.

**Comment by CodeCrafter-TL** [comment]
Don't worry I will do that
